### ISSUE TITLE
Custom fields dont work

### ISSUE THREAD

**Issue by andreysneg** [qtranslate/qtranslate-xt#1061]
Custom configuration is so hard and where is normal documentation ?
i18n-config.json - so many strange things here :)
This is one of the reasons for the low popularity - nobody understands how to make a configuration .

I have custom Tinymce field at post editor page. id="mceu_24"
https://bit.ly/2WJ97N0

I simple try Custom fields ID or Class - https://bit.ly/3gTqiSZ

And dont work nothing.

**Comment by herrvigg** [comment]
Yes it is hard. 
The format is what it is. I have been trying to simplify it but it's not that easy.
The documentation is in the Wiki: https://github.com/qtranslate/qtranslate-xt/wiki/JSON-Configuration
There are many "shortcuts" possible to make the config file less verbose by avoiding to repeat some keys, but it's actually generating a lot of confusion. I would prefer a less flexible format but a simpler structure, even if it's more verbose.
You can achieve the same programmatically in PHP but if you can with JSON it's better because that format may evolve.

Integrating a custom TinyMCE editor is even more difficult because it depends on its initialization sequence and that can vary a lot. The problem is also if the fields are created after the page is loaded, but I don't know if this is the case here (what does the Tab 1 and Tab 2 do?).

I'd suggest you first start with simpler fields like the "Simple Text" on your screenshot.
You can try giving an ID or a class in the config, but that works for basic pages such as "post".
Using a JSON config is more flexible. If your config is correct and the field is available before the page loads, new hidden HTML elements are created and you should see the translatable bar on the left.
