### ISSUE TITLE
assert() warning in PHP 7.4 and E_COMPILE_ERROR in PHP 8.0

### ISSUE THREAD

**Issue by Komarovski** [qtranslate/qtranslate-xt#1082]
Hey everyone,
In my PHP log I have warnings about using of function `assert()`, here's the example of warning:

```
PHP Warning: assert(): detected in parse_language_info - cancelled by can_redirect, url_info={
&quot;cookie_lang_front&quot;: &quot;ru&quot;,
&quot;cookie_front_or_admin_found&quot;: true,
&quot;scheme&quot;: &quot;https&quot;,
&quot;host&quot;: &quot;example.com&quot;,
&quot;path&quot;: &quot;\/&quot;,
&quot;query&quot;: &quot;wc-ajax=aws_action&quot;,
&quot;path-base&quot;: &quot;&quot;,
&quot;doing_front_end&quot;: true,
&quot;wp-path&quot;: &quot;\/&quot;,
&quot;language&quot;: &quot;ru&quot;,
&quot;doredirect&quot;: &quot;detected in parse_language_info - cancelled by can_redirect&quot;,
&quot;set_cookie&quot;: true
} failed in /home/hostaccount/example.com/www/wp-content/plugins/qtranslate-xt/qtranslate_core.php on line 105
```

I get this warnings with PHP 7.4 version, when using search plugin "[Advanced Woo Search](https://advanced-woo-search.com)". Plus, I found that in PHP 8.0 `assert()` function will throw error - [assert() on php.net](https://www.php.net/manual/en/function.assert.php#refsect1-function.assert-changelog).

Here's the list of files where `assert()` function are presented:
`qtranslate_core.php` - lines 105, 314, 360, 375, 408, 473
`admin/qtx_admin_gutenberg.php` - line 68
`modules/acf/src/plugin.php` - line 357
`modules/acf/src/acf_5/fields/file.php` - line 193
`modules/acf/src/acf_5/fields/post_object.php` - line 113
`modules/wp-seo/wp-seo-admin.php` - line 8

So, the question is - are we still need to make this checks with assert function, or we can remove them?

**Comment by herrvigg** [comment]
In my case, I have no assert triggering at all. I run with PHP 8.0 but it was also fine with PHP 7.4. So in the present case the integration with Advanced Woo Search seems to be the main reason.

I'd rather leave the asserts, because they show real problems. It's often due to very special cases of integration. In the current state when there is such an assert QTX can't recover properly. 

The error handling can potentially be improved to avoid this by making the plugin more robust, but this requires more work as WP is a fragile environment for the integration and QTX is quite complex. In some cases, the error could be ignored, but in other cases it could be really problematic. It is very difficult to predict, it depends on every use case.

Normally, in production you could even turn all the asserts off in your PHP config, see: https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting#development-vs-production-mode. But it is better to keep them and investigate about each case.

**Comment by herrvigg** [comment]
But it's good you mention [this change with PHP 8.0](https://www.php.net/manual/en/function.assert.php#refsect1-function.assert-changelog) that I wasn't really aware of.
```
PHP 8.0.0 - Declaring a function called assert() inside a namespace is no longer allowed, and issues E_COMPILE_ERROR.
```
There's something I still don't understand, if this raises a compile error I should even see it but it's not the case. Is it raised at compile time or runtime? 🤔

**Comment by herrvigg** [comment]
No, wait, there's a confusion here. The change in PHP 8.0 is about _declaring_ a function called `assert`, not _calling_ an assert 😅 .
It would have been surprising they banned any assertions! So yes, QTX uses `assert` and it's fine to do so.

The problem you encounter is the most common one, about redirection. QTX requires a [redirection](https://github.com/qtranslate/qtranslate-xt/wiki/Browser-redirection) but in this case it's not `doing_front_end && qtranx_can_redirect() == false` so we are in troubles.

**Comment by herrvigg** [comment]
As a quick check you can comment the assert line 105 and see how it works but I can't say anything about the impact, it depends completely about your website and what the HTTP request is about. So you should look more into the code, ideally with breakpoints in a debugger (I use Xdebug) or just add some traces if you can't do otherwise.

Perhaps we should have a special hook to delegate the redirection error handling to the users, by default it would assert in QTX but that starts to become quite twisted.

**Comment by Komarovski** [comment]
> No, wait, there's a confusion here. The change in PHP 8.0 is about _declaring_ a function called `assert`, not _calling_ an assert 😅 . It would have been surprising they banned any assertions! So yes, QTX uses `assert` and it's fine to do so.
> 
> The problem you encounter is the most common one, about redirection. QTX requires a [redirection](https://github.com/qtranslate/qtranslate-xt/wiki/Browser-redirection) but in this case it's not possible due to `doing_front_end && qtranx_can_redirect() == false` so we are in troubles.

Oh... Sorry :) I've quickly read the article about assert on php.net and didn't noticed that it's about declaring a function, not calling. 🤦‍♂️
