### ISSUE TITLE
WC: attributes edit page fields not shown

### ISSUE THREAD

**Issue by spleen1981** [qtranslate/qtranslate-xt#1162]
Woocommerce attributes edit page `input` fields are hidden due to parent `td` `display` property is set to `none` trough QTX javascript.
Hence the above setting page is not usable unless the `display` property is manually changed after page is loaded.

**Comment by herrvigg** [comment]
It's not generic QTX or the WC module but QTS itself that disables it in `qts_hide_term_slug_box`.
https://github.com/qtranslate/qtranslate-xt/blob/f6efc8b37757ebd5b607c760bf53aff56300603d/modules/slugs/includes/qtranslate-slug-admin.php#L434-L441

There was probably a good reason for hiding this because it would break something. But now with the knowledge you have you may take a better look. I suggest we try to fix it in #1161.

**Comment by spleen1981** [comment]
You are right, see https://github.com/qtranslate/qtranslate-xt/pull/1161#discussion_r867383060 and https://github.com/qtranslate/qtranslate-xt/pull/1161/commits/d3e7688769fd00ec839fd26e2f457f1cc4f4f122
