### ISSUE TITLE
error during slugs uninstallation after successful migration

### ISSUE THREAD

**Issue by Hr0bar** [qtranslate/qtranslate-xt#1184]
Hi, experienced this error when pressing the uninstall button of qtranslate-slug and it did not uninstall:

`AH01071: Got error 'PHP message: PHP Fatal error:  Cannot redeclare qts_get_url() (previously declared in /opt/bitnami/wordpress/wp-content/plugins/qtranslate-xt/modules/slugs/src/slugs-utils.php:7) in /opt/bitnami/wordpress/wp-content/plugins/qtranslate-slug/qtranslate-slug.php on line 126', referer:`

Not sure if solvable without renaming qts_get_url :/

**Comment by herrvigg** [comment]
Yes it would clash when used at the same time. An easy workaround is to disable the Slugs module or the qTranslate-XT plugin before you uninstall QTS and enable all back after that. Be sure your migration is complete by checking the migrated slugs in post/pages (postmeta) and in the slugs settings (termmeta and options).

We should have renamed these functions, all `qtranslate` functions should at least be prefixed by `qtranxf`. That also applies to the other modules as ACF, WooCommerce... though in that case there's a plugin check because we know where the plugin path of the default install.

But that's not the best way to do it, I'm thinking of introducing namespaces in the next major release (V4). WordPress is not showing the good example either, they have a bunch of global functions, just a few prefixed with `wp_`. They should use namespaces but they look quite stuck with their legacy API. I would be more radical, deprecate old stuff in a major release and give some time but force active plugins to change.

**Comment by herrvigg** [comment]
Fixed in master.

**Comment by herrvigg** [comment]
Fix released in 3.12.1.
