### ISSUE TITLE
wp-admin "domain" redirected you too many times

### ISSUE THREAD

**Issue by angelsnails** [qtranslate/qtranslate-xt#1236]
Hello, i'm having an issue with accessing my website while connected to my wp-admin account. The problem is resolved once i deactivate this plugin. 

Do you have any ideas as to how to fix it?

Thank you in advance

**Comment by yycgk** [comment]
From my wp-admin account on pages, if i select "view", i get this error message. The problem is resolved once i deactivate this plugin. Does anybody know how to fix it? Thanks!
![Screen Shot 2022-10-21 at 4 10 29 PM](https://user-images.githubusercontent.com/116393455/197296030-c7ede494-f077-4ef3-bf7b-9305971388c4.png)

**Comment by herrvigg** [comment]
This is impossible to investigate without more information from your side. See [wiki troubleshooting](https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting).

**Comment by herrvigg** [comment]
Do you have some special configuration, what are the URL Modification Mode and cookies settings?
See config from options-general.php?page=qtranslate-xt#troubleshooting
Redirection loop is often a sign there's something wrong with cookies that can't be written or read.

**Comment by herrvigg** [comment]
We'd need something better in QTX to detect these misconfigurations before running into these bad redirection loops.

**Comment by herrvigg** [comment]
Duplicate #1056, I'll regroup all these tickets to that one.
