### ISSUE TITLE
front-end user don't show qtranslate-x tabs

### ISSUE THREAD

**Issue by herrvigg** [qtranslate/qtranslate-xt#192]
<a href="https://github.com/bebenou"><img src="https://avatars1.githubusercontent.com/u/13213770?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bebenou](https://github.com/bebenou)**
_Tuesday Jul 07, 2015 at 05:57 GMT_
_Originally opened as https://github.com/qTranslate-Team/qtranslate-x/issues/192_

----

Hello
I use wpresidence theme, qtranslate-x works almost perfectly with it.
If I add a property on the admin page add property, languages tabs are here and it works fine, but when a user wants to add a property on the front-end user page there is no tabs! Is that a bug or is there a simple way to add it with a code to copy past somewhere maybe? (also custom fields used for amenities are not translatable)

I saw that wpresidence is a very successful theme and all real estate agents need to translate their website in few languages, after using all translating plugins I can say that qtranslate-x is the best and easiest. thanks

**Comment by Aldo-ACE** [comment]
Hello...
Im use WPResidence and now im using xtranlste-XT.
I have similar problem as "bebenou". I use the front tend just for us, not for pubplic clients.
The translation works fine in the description using the tags " [:en] "but this doesn´t work in the title.
In WPR customer servce says is because HTML is not supported by security reasons, but is this "[:en]" an html code?. It is working perfect in description field from front-submission page.
https://prnt.sc/pympvo

And Im not able to translate custom fields, even if I type the "class" or "id" of the element in the qXT integration menu, like : reference-number  for id="reference-number"

https://prnt.sc/pzkj4b

Im apreciate any comments.

Thanks.
