### ISSUE TITLE
Next and Previous Post in Single Page

### ISSUE THREAD

**Issue by emyawasap** [qtranslate/qtranslate-xt#598]
Hi I am having issue in `get_next_post()` and `get_previous_post()` it is including untranslated posts. 

![image](https://user-images.githubusercontent.com/11808545/43188773-8bb6a8a0-9027-11e8-9557-f4a613783093.png)

Here is how I implement the code.
![image](https://user-images.githubusercontent.com/11808545/43188840-c0f4ea90-9027-11e8-825b-06807b813c00.png)

**Comment by herrvigg** [comment]
If i understand it right, your post with title "Natural Language Processing 101" is not translated and here it appears nonetheless as the next post.

I see there are some filters to exclude the adjacent posts (get_previous_post_where and get_next_post_where) if they are not translated. But those are only enabled if you have the option `Hide untranslated` checked. Can you look in your options `General` / `Untranslated content` /  `Hide untranslated` and see the status of this option?

By the way which qTranslate-X are you using? The official release or this master branch from this new repo? (this part is unchanged so it's just to know)

**Comment by herrvigg** [comment]
Great! :)

The new repo is not available as plugin yet because it's still too tightly coupled to the old qTranslate-X. It's a shame the author disappeared and he was the only one of the "qTranslate Team". But you can experiment it simply by cloning this git repo. The master branch works perfectly for me and you will already benefit from new features such as "Copy from" that were never released. You can have both qTranslate-X and qTranslate-XT installed, but you need to activate only one at a time. Also be aware they still share all the same options at the moment.
