### ISSUE TITLE
Any plans to integrate GravityForms support in core?

### ISSUE THREAD

**Issue by reddo** [qtranslate/qtranslate-xt#610]
There already is a [plugin](https://github.com/mweimerskirch/wordpress-qtranslate-support-for-gravityforms), which sort-of-works by manually adding the `[:en][:]` to the fields, but I would love to see the switch buttons work.

Great work taking this project over, I was getting worried I might have to migrate and was **not** looking forward to the headache that comes with that. Kudos!

**Comment by herrvigg** [comment]
Interesting to see they are many add-ons.

This one is very compact so it would not be a big deal. But on the long-term i think the best would be to setup a modular system in qTranslate with all add-ons as optional, such as done in Jetpack for example. Going together with this, there is the need to define a clear API so that qTranslate can evolve internally without breaking such integrations.

Currently the code is a big mess, there is no design structure with global functions everywhere. The file structure is kind of ok. I've started doing a lot of cleanup on the code but i haven't refactored anything yet. Maybe having all the add-ons in a first step could help having a better control on the evolutions. One day we might come to it but i can't tell when :P

So for the moment it's better to keep them as they are because you have better clue how to use them.

**Comment by herrvigg** [comment]
Another point is the integration in the admin pages for managing the language switches. I don't know GravityForms but it looks like a form editor. If i understand well your github add-on handle the data transfer (mails and maybe more). But you are still editing the forms in raw mode. Currently the integration on admin side is done through i18n configuration files in json format. I don't find it very intuitive but at least it should work. You can check the existing json config files in qtranslate-xt/plugins and try to define a new one for your needs.

**Comment by herrvigg** [comment]
We should handle the GravityForms plugins as the one for WooCommerce. Imo it's easier if these add-ons are fully integrated in the main project as optional modules, rather than having separated github projects. The maintenance should be much easier, both internally and through PRs submitted by the users.

I can't really test GravityForms since it requires a licence which i don't have, but if you give me the name of main plugin file i can create a separate branch for test that you can test. It should work exactly the same way, provided you have standard installations in default paths. I will start by merging the last version of your add-on plugin.

The "plugin filename" in the sense of a WP plugin should also include the name of the plugin folder. Examples:
```
qtranslate-X/qtranslate.php
qtranslate-XT/qtranslate.php
woocommerce/woocommerce.php
```

Let me know and we can try this :)

**Comment by reddo** [comment]
That one's not my plugin, but I'm glad to help any way I can. Editing the form fields, labels, descriptions etc works in raw mode with that plugin. The Gravity form plugin is in `gravityforms/gravityform.php`.

**Comment by herrvigg** [comment]
Thanks!

So here is a branch `gravity-forms` where i have integrated your plugin as a new add-on module. The code is strictly the same as your plugin so you can experiment with this (`git checkout gravity-forms`).

https://github.com/qtranslate/qtranslate-xt/tree/gravity-forms

The main idea is that i check if gravity forms is installed and active. In that case i look for the legacy plugin and try to deactivate it if it is also active, because it would be incompatible with this new add-on. If the automatic deactivation fails an error message is shown in the admin page. 

What is not handled is if you ever re-activate the legacy plugin later but then you will get nasty errors due to conflicting names so it should be quite clear you shouldn't do that ;)

**Comment by herrvigg** [comment]
Previously, the GravityForms plugin was looked under 'gravity-forms-addons/gravity-forms-addons.php` before displaying a notice for integration. This was supposedly the name of the main Gravity Forms plugin but you provided me a different name. I believe you have a more recent version so i will rather stick to what you gave, but do you have any idea if this has changed under the last months/years?

**Comment by reddo** [comment]
I'm really sorry for the late reply, it's been a hectic week for me. I don't think the plugin was ever in the `gravity-forms-addons/gravity-forms-addons.php` location, at least not since I've been using it (going on 3 years now). I'm usually on the latest version, I keep everything updated.

**Comment by herrvigg** [comment]
No worry, there's zero emergency :) Just let me know how it goes when you have tried it.

**Comment by herrvigg** [comment]
@reddo i've merged here in the gravity-forms branch a new module manager (that i wrote for the woo-commerce branch). This one should be better so you're welcome to check this with Gravity Forms.

**Comment by reddo** [comment]
@herrvigg I've checked out the branch and made another small PR to it, but otherwise it seems to be working. I say it's safe to merge to master.

**Comment by herrvigg** [comment]
Awesome! Will do soon together with woo commerce.

**Comment by herrvigg** [comment]
Merged into a new `modules` branch and PR sent: https://github.com/qtranslate/qtranslate-xt/pull/627
