### ISSUE TITLE
Support CPT UI

### ISSUE THREAD

**Issue by homeandriy** [qtranslate/qtranslate-xt#615]
Is it planned to support this plugin in the future [Custom Post Type UI](https://uk.wordpress.org/plugins/custom-post-type-ui/) ?

Since when you create you have to enter in the field as follows:
![image](https://user-images.githubusercontent.com/8323670/47072147-1d672f00-d1fe-11e8-8bdc-9ef2e3c76b85.png)

**Comment by herrvigg** [comment]
This should be handled as an integration feature on the front-end side. I've never had to use this but it should be possible. It's a good study case since i'd like to refactor the integration framework :P

I find it personally quite complicated but the main idea is that you define some rules in some i18n json files to handle these fields. You can check how it's done in the main `i18n-config.json`. For more help check the documentation: https://qtranslatexteam.wordpress.com/integration/

**Comment by herrvigg** [comment]
See https://github.com/qtranslate/qtranslate-xt/wiki/Integration-Guide
