### ISSUE TITLE
I want to donate?

### ISSUE THREAD

**Issue by LaMpiR** [qtranslate/qtranslate-xt#636]
Hi good people.

Awesome that you are trying to restart this plugin and I would Like to donate money. Do you have anything organised?

Best regards

**Comment by herrvigg** [comment]
hello,
nice of you! Nothing organized at this point and i can't tell much more for now since i do it on my free time. Maybe this could help to have a small server, and possibly finance the licences of development tools. I think we'll bring back this question when we have clarified a bit the future of this plugin (official plugin, under the qTranslate brand or not).

**Comment by herrvigg** [comment]
Maybe we'll rediscuss this with the new project, no plan for now.
