### ISSUE TITLE
XSS vulnerability in IE (only IE)

### ISSUE THREAD

**Issue by arku31** [qtranslate/qtranslate-xt#639]
https://github.com/qtranslate/qtranslate-xt/blob/35ab2931a52f9d81ca4d016de7a1640ff7c7a14a/qtranslate_core.php#L1268

**How to check?**
Open in IE (not edge) http://live.paresh.ninja/redirect.php?u=https://localhost/en/"><svg/onload=alert(document.domain)>/%252e%252e/x

**How to fix**
Please, escape this with esc_url
`$complete = esc_url(qtranxf_buildURL($urlinfo_lang,$homeinfo));`

**Comment by herrvigg** [comment]
hello @arku31 
thanks for this! A few questions:
- if that's only for IE isn't that more of a security issue of that browser?
- which version of IE? I tried with IE 11 (11.253.17763.0) but didn't see anything special. What is that suppose to do, show the alert message?
- which URL mode are you using? I suppose QTX_URL_PATH which is the default. Do you think it will work also with QTX_URL_DOMAIN / QTX_URL_DOMAINS / QTX_URL_QUERY? The domains modes are hard to test...!
- if the `urlinfo_lang` already contains something escaped, what happens? I'm not sure how risky the change is, i just want to be sure it won't create some regressions.

**Comment by arku31** [comment]
- This is a security issue of that browser but that's IE... :) It's no longer supported but still in use
- Any IE. I forgot to mention, you should call this function, I'm using it like this `<?php echo qtrans_convertURL(get_permalink(), 'en'); ?>`
- Right, the default one
- Shouldn't change anything, but... I found regressions as well =( link with "&" are also encoded, so it brokes website, links with "&" leads to permanent redirect. I'm looking for another solution ATM.

**Comment by herrvigg** [comment]
@arku31 After looking at this i find it a bit too specific and out of scope for qTranslate.

Since this is a security issue that modern browsers apparently deal with, it's more of a hack to compensate for a limitation in the old IE, because it's not maintained anymore. Though the proposed change is very small, and i thank you for that, i'd like to avoid adding an extra layer of complexity only for an outdated IE 😬 ... that no one should use anymore :sweat_smile:

What i suggest is you try to use the hook `qtranslate_url_set_language`. Ideally you'd like a hook after `qtranxf_buildURL` (there's actually some commented code about it!). But maybe by looking at the fields `$urlinfo [wp-path]` and `$urlinfo[query]` you could be able to handle it with the existing hook just before. Let me know if it works.

**Comment by herrvigg** [comment]
Oh i read a bit quickly and didn't think it was still the case with IE11. So roughly IE has still 6% of the browser share: https://www.stetic.com/market-share/browser/.
It's a small change but we have to evaluate a bit better the implications, i still have mixed feelings about it.

**Comment by arku31** [comment]
I can only say that it works fine for more than one month in production mode but can't say that all supported modes&etc works fine as well - never tested. To be honest, I do not use the "-xt" at all :) Anyway it sounds logical - we have to validate&sanitize any user input before output :)

**Comment by herrvigg** [comment]
Looking into the existing code I also found this in `qtranslate_core.php` line 60:
`$url_info['query'] = qtranxf_sanitize_url( $url_info['query'] ); // to prevent xss`
So there is already something done related to XSS but now let's see for the other part you added.

Can you explain better how to reproduce the problem? I really don't understand how to run your example:
- you gave two rows, should they be appended?
- what is this: `/%252e%252e/x` ?
- what is supposed to be running as localhost?
- what is the problem expected to be seen?
- what do you mean later with "you should call this function, I'm using it like this  `<?php echo qtrans_convertURL(get_permalink(), 'en'); ?>`". Where should this be called?

**Comment by herrvigg** [comment]
@arku31 could you explain better this? I also looked at `qtranxf_buildURL`, it can't be replaced like this with `qtranxf_sanitize_url`, these functions don't do the same. Maybe the sanitize should be done on top of the resulting URL but we'd need more information to proceed.

Btw is there any reason for using qTranslate-X and not -XT? The -X version remains way behind now.

**Comment by arku31** [comment]
Hi,
1. This is basically one row, it was cut by github. So just single line it.
2. No idea to be honest. Not sure that it's important
3. nginx+php-fpm but I guess it's server independent
4. The problem is that there is possibility to pass any custom javascript to the page
5. I'm calling this on theme index page, so it would be enough to just call this function on blank file
6. I'm using -X version because it was already modified and I don't really know what was modified.

I can record a video how to exploit it but since I don't have IE it would be a bit complicated but if required - I can, should I?

**Comment by herrvigg** [comment]
I have an old IE 11 and I don't manage to replicate it. The encoded string should be important, if it's not why did you give it? It's hard to follow what you are trying to illustrate. Maybe a video could help indeed.

**Comment by herrvigg** [comment]
Not yet sure about the fix here but this issue is probably related to https://github.com/qtranslate/qtranslate-xt/issues/693.

**Comment by herrvigg** [comment]
@arku31 coming back to this. Please can you give me a proper example of the problem? It's too cryptic to be understood.

Imo it's wrong to use `esc_url($qtranslate_url)`, because you use the default context which is for display. The URL is processed internally so this is likely to break queries for example with ampersands when used to give real parameters in the query string. For now I prefer not to do this change in its current state.

**Comment by herrvigg** [comment]
@arku31 keep us updated if you want the issue fixed. I close for now, feel free to re-open if you can provide more info.
