### ISSUE TITLE
qtrans_front_language cookie

### ISSUE THREAD

**Issue by hubosh** [qtranslate/qtranslate-xt#644]
Does this affect security considering that it only runs http not https ?
and how can I make it https

**Comment by herrvigg** [comment]
Sorry i don't understand the problem. I'm using both http and https, everything works with the front cookies.

**Comment by Ruaphoc** [comment]
I believe the issue is when served over HTTPS the cookie is missing the “secure” attribute. This will get flagged by security scanners, but setting it prevents access to the cookie over unsecure connections (HTTP). HTTPS is very easy to implement these days, so should be enabled on all sites, but this is the “Real World” TM, so we can’t assume this is the case. Maybe a toggle on the setting page to enable the secure property on cookies?

**Comment by herrvigg** [comment]
If i understand it correctly, this option is already available (in the advanced tab):

![image](https://user-images.githubusercontent.com/19155375/52821024-ecb0dc80-30ad-11e9-8ba2-d986a3ad8978.png)

@hubosh did you try this option?

**Comment by herrvigg** [comment]
An old issue existed about the **admin** cookie where the flag is not set for `secure` but neither for `httponly` (which is another flag): https://github.com/qtranslate/qtranslate-xt/issues/467. Now i'm considering to add this `httponly` option and share these options both for admin and front cookies. Let me know in that ticket if this makes sense.

@hubosh concerning the secure flag for the front cookie it's already available and i suppose you just missed the option so i close this issue. Re-open it if you still have a problem.
