### ISSUE TITLE
Uncaught ReferenceError: qTranslateConfig is not defined

### ISSUE THREAD

**Issue by k9t9** [qtranslate/qtranslate-xt#657]
##### Context 
Admin area --> custom plugin settings page.
##### Problem
Language flags ( LSB? ) are not showing, and I am getting the following console  error 
```
Uncaught ReferenceError: qTranslateConfig is not defined
    at common.js?ver=3.5.1:1393
(anonymous) @ common.js?ver=3.5.1:1393

``` 

it seems the context is not available  ( maybe related to #654  ) 
##### Other maybe relevant data 
After manually adding the `qtranslateConfig` var ( with a manual `admin_footer` hook echo hack ) it shows up.
Seems like the hook that calls the function to echo the var is not working ?
##### Version
Tested with Version 3.5.4.

**Comment by herrvigg** [comment]
Are you talking about the main plugin page listing all available plugins? Why would you need the LSB there? There's nothing to edit so by default the LSB are not supposed to be loaded on that page, only the flags and some CSS is loaded (and we probably don't even need that). Maybe you have some specific i18 configuration.

The question with the context is rather related to https://github.com/qtranslate/qtranslate-xt/issues/650. The goal of the fix was to make the function available ASAP, before DOM is fully loaded so it's harder to do better than this. Maybe you have a script loaded before qTranslate-XT trying to do stuff it's not supposed to do at that time.
- in general you should try to do stuff after the DOM is loaded (e.g. with `$(function () { some_stuff_using_qtx });`)
- if you really need to it earlier you can try to call `qTranslateConfig.js.get_qtx` before qTranslate itself loads it.
- if you don't even have this `get_qtx` available, you have to review your JS dependencies and load stuff in the good order.
- but if you don't even have `qTranslateConfig` object then it's something else.

**Comment by herrvigg** [comment]
@k9t9 sorry i can't understand what the problem is. I close for now, feel free to re-open with more information.
