### ISSUE TITLE
Can't update to 3.6.0

### ISSUE THREAD

**Issue by LaMpiR** [qtranslate/qtranslate-xt#663]
It's showing that I can update it to new version which is marked as 3.6.0.dev. and when I try to do the update, in the end it's saying that the update is over, but it is not, since I keep getting the update message again.

Du hast Version 3.5.5 installiert. Aktualisiere auf Version 3.6.0.dev. 

Herunterladen der Aktualisierung von https://api.github.com/repos/qtranslate/qtranslate-xt/zipball/3.5.5?access_token=xxxx …
Entpacken der aktualisierten Version …
Die aktuelle Version wird installiert …
Entfernung der alten Version des Plugins …
Das Plugin wurde erfolgreich aktualisiert.
Abschalten des Wartungsmodus …

Alle Aktualisierungen wurden vollständig durchgeführt.

**Comment by herrvigg** [comment]
Ah right, are you using github updater? The reason is i didn't create a github release so it looks for it but can't download it. I may just revert the version in the WordPress header to avoid this annoyance. I wanted to do a bit more experiments first before releasing it.  Since we are not an official plugin yet, i prefer to release only "final" version on github after tests. It could be enough to keep the version in the PHP variable, this is more for caching reasons.

For most users it should not change a lot. The most relevant part is actually for WooCommerce since it brings the last version of the old integration plugin as a module. But i really think this could be a better way to handle the extensions to qTranslate without going in the overhead of the WordPress plugins. It can potentially evolve to something easier to manage for all the integration, not only the built-in part.

**Comment by LaMpiR** [comment]
I am using github updater :)

No worries, when you think it's ready, I will update it.

Thank you for your effort!

**Comment by herrvigg** [comment]
OK done, i prefer to revert this version for now and let a few days for testing. More modules and targeted fixes for those may also follow. I don't remember if you can force a refresh in github-updater, but it should now come back to 3.5.5.
