### ISSUE TITLE
Can you host qtranslate-xt within the public wordpress.org repository (again)?

### ISSUE THREAD

**Issue by Blackbam** [qtranslate/qtranslate-xt#674]
Guys thank you so much for developing this further on and also for new major release two days ago. Can you host this again within the public wordpress.org plugin repository again - in order to enable auto-updates, automatic install, gain more attention and so on?

Because currently we always have to update all of our projects manually (or with the Github-Updater Plugin, as recommended). Maybe we just can put some notice like "you can not enable this plugin as long as you are not using the classic editor plugin" or something like that, until Gutenberg support is available.

One reason is also that I can reason towards customers why we should use this Plugin for the project, because currently some say "this is not even on the public repository".

**Comment by herrvigg** [comment]
It's not just about pushing to wordpress.org, for more details see https://github.com/qtranslate/qtranslate-xt/issues/601 and https://github.com/qtranslate/qtranslate-xt/issues/648.

Creating a new plugin is the next big goal, before Gutenberg or anything else. We'll get there but there is a lot of preparatory work first with the migration of the options. Also there are many things i dislike in the options/settings and how the data is handled in the hooks. It is not viable and it has already become crucial to refactor some parts. This is the right moment to do it or some of this mess will stay for long... and i can't stand it anymore.

This is managed on free time so it will go slowly, it's about patience and quality. There are many official plugins that are not maintained and official has never meant quality. If the customers have money they should go for commercial products, otherwise they have to adapt and deal with what is available. If developers help with PR it also helps but reviews and impact analysis also take time, plus the fact there is no test so the core part is currently very fragile and risky to change.

**Comment by Blackbam** [comment]
>  If the customers have money they should go for commercial products, otherwise they have to adapt and deal with what is available.

Well I do not recommend qTranslate because my customers do not have money, but because I think it is the only good architectural approach.

Multisite multilanguage is not a good solution - recently I worked for a company which has a multisite installation where each site of the network serves a country. You need a multilanguage plugin as there are multiple languages within one country.

WPML is also not a good solution. They **_duplicate every post_** . In a corporate context I sometimes have 200 custom fields on some page or post type but only three labels. I want to translate the text fields and thats it! Not create another post.

**qTranslate always handled this the best way** - it is free and I simply translate the texts **_within_** a single post. I know the code in the core is messy thank you so much for doing the hard work of extending this. The architectural concept of qTranslate should be preserverd no matter if you replace (parts of) the core or not.
