### ISSUE TITLE
not work in wordpress 5.1.1 and woocommerce 3.6.2

### ISSUE THREAD

**Issue by Dezueka** [qtranslate/qtranslate-xt#676]
The version of yours 3.6.0 is not working on the wordpress 5.1.1 and woocommerce 3.6.2 the admin backend begin with the blank page.

**Comment by aerostitch** [comment]
When you go to the plugins page you should see the following I guess (at least that's what I see when upgrading the plugin:
```
Block editor (Gutenberg) not supported in qTranslate‑XT yet! Please install and activate the Classic Editor plugin.
```
I'm guessing that's the issue as the block editor is the new default editor.
Is there any timeline for this support?

**Comment by herrvigg** [comment]
I haven't seen such problem with the blank page so far, it seems to work for most users. Indeed there should be the admin notification for the Classic Editor. What happens if you install the Classic Editor as suggested? Did you reactivate qTranslate-XT?

> Is there any timeline for this support?

About Gutenberg, no date, this is not the priority. For the full stack developers you can play with the experimental branch: https://github.com/qtranslate/qtranslate-xt/tree/exp/gutenberg. I have updated it recently. The proof of concept works but it's only experimental, there's a lot to do and test. This is a whole separate task and i don't want to slow down the more important core changes with this.

**Comment by herrvigg** [comment]
It may be due to other conflict but i can't reproduce this problem and it seems to work for other people so i close this. Gutenberg support will take much more time.
