### ISSUE TITLE
Please fix styles

### ISSUE THREAD

**Issue by Tusko** [qtranslate/qtranslate-xt#697]
Hello!
Please fix styles in admin area for multilanguage inputs
http://cl.ly/d1692f

**Comment by herrvigg** [comment]
@Tusko mmm... i don't know if you are aware but this is what i get from your website:
```
Attackers on d3a1eqpdtt5fg4.cloudfront.net may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards).

Google Safe Browsing recently detected phishing on d3a1eqpdtt5fg4.cloudfront.net. Phishing sites pretend to be other websites to trick you.
```

Not the most trustworthy thing to see. Anyway i could see the link. Btw why don't you just send a normal text instead of an image seen it's basic CSS? Weird. Also describing the change a bit can help. The CSS is only for ACF, `.multi-language-field -> height: auto` in if i got it right.

**Comment by herrvigg** [comment]
Also, `height: auto` is the default CSS. Why would need that? Can you show us what is about? You can copy-paste images directly in github.

**Comment by Tusko** [comment]
@herrvigg 
![image](https://user-images.githubusercontent.com/2039259/58747071-a28e1400-846e-11e9-9c00-29e24e15a989.png)

Some fields have fixed height 28px (ACF Pro)
![image](https://user-images.githubusercontent.com/2039259/58747090-dc5f1a80-846e-11e9-90bb-4e53368d7cc8.png)

So, these styles will that bug
`.multi-language-field -> height: auto`

**Comment by herrvigg** [comment]
OK i see. Thanks for the explanation, it's now fixed in the ACF module.

However i suggest you also send a small PR to the plugin this module is derived from: https://github.com/funkjedi/acf-qtranslate

It seems the author still maintains it. For now the module and the plugin live their own life so we need to sync them separately. This will make our life easier if we have to resync and other people still not using qTranslate-XT might also want this. We'll deal better with this question later.
