### ISSUE TITLE
Jetpack related post titles are not translated

### ISSUE THREAD

**Issue by dobek** [qtranslate/qtranslate-xt#699]
I have Jetpack and I use related post features.
It generates thumbnails of posts 
Unfortunately, the title of post is not translated and qtranslate tags a visible there e.g. "[:en]Comparing Psychoanalysis and Zen[:]"

REPRODUCTION
1. Go to: https://blog.dobek.org/en/2019/05/28/lotus-sutra/
2. Scroll to the end of the post - you will see related posts with thumbnails
3. Titles contain language tags e.g. [:en], [:pl], [:], etc

**Comment by herrvigg** [comment]
Indeed i can reproduce it. I'll try a few things later, i just hope Jetpack allows a fix with its current API.

**Comment by dobek** [comment]
Thank you. It would be nice to have this fix. It makes an impression that the page is not reliable.

**Comment by herrvigg** [comment]
@dobek i have some news about this.

I looked into Jetpack and it is quite of a mess! But now I understand how it works. See `jetpack/modules/related_posts/jetpack-related-posts.php`:
- it registers a `rest_get_related_posts` callback (REST API)
- when a post is shown, a asynchronous query is made to get the related posts through this entrypoint
- lots of stuff is done to get the IDs of the related posts, but we don't care about this
- the whole data is fetched in `get_related_post_data_for_post`, this is what we are interested in.

*However* they load each related post data with get_post($post_id) but they use the default filter which is `raw` and not for `display`! Therefore the usual callbacks such as `the_title` and `the_content`, which are ensuring the translations, are not called -.-

So why is the content translated? It's actually the excerpt (by default coming from the content) and it's just a case that it gets translated because they call `wp_trim_words` which is hooked by qTranslate-XT and parses our language tags! But this is not done for the title when it's not empty (see `_get_title`).

By chance there is ultimately a filter `jetpack_relatedposts_returned_results` called before returning the results. I'm now trying to setup a filter with the hope to hack the results (yet another hack) but i haven't managed to make it work yet. If someone wants to try or succeed let me know. But i think this should be feasible.

**Comment by herrvigg** [comment]
Fix available on the master branch, i tested it in production and it should work now!
Note Jetpack does not allow to enable this feature on localhost (it uses some web services linked to the website).

Important: you need to reactivate qTranslate-XT so it can load the new module that i created for Jetpack.
I hope you can test it with github, otherwise patience a new release will come soon.

**Comment by dobek** [comment]
It works now. Thank you very much :).  However, I see another issue. I will create a new ticket for it.

**Comment by dobek** [comment]
I created #716 to report the found issue.

**Comment by dobek** [comment]
@herrvigg - once again - thank you for solving the main issue :).

**Comment by herrvigg** [comment]
Good to read :)
