### ISSUE TITLE
 Hide URL language information for all languages

### ISSUE THREAD

**Issue by shambolik** [qtranslate/qtranslate-xt#700]
Hey all, I think it would be useful to have the option to hide all languages in the URL and not just the default. In the mean time is there a way to do that by adding custom JS to a theme or something like that?  Cheers ;)

**Comment by Pandiora** [comment]
The content could be determined by a cookie which picks the language. I think ppl are using different urls because of SEO and this way your idea wouldn't be the best and just some cosmetic enhancement. Prove me wrong, but I think php just delivers the content for the specified language. So in order to get what you want and by using JS, you would have to deliver the contents of all languages. And this in turn wouldn't be a good practice if you have several different languages on your blog, for one and the same post. The closest you could get to what you want, would be to use url-parameters (?lang=en), which is also not optimal for SEO.

I could just give the advice to you to look at how larger companies deal with this. Google i.e. has different .tld for every country. facebook uses en_us.facebook.com i.e. and others just use /en/category/speaking-url. I can understand why you like the idea, but I don't think this is going to happen anytime soon. If you really want to do this by yourself, you would have to learn and rewrite php.

**Comment by herrvigg** [comment]
@shambolik Technically speaking, it is something that should be feasible - but only from the user point of view. I know more or less where it is handled in the code. However as @Pandiora mentioned, the first problem is the SEO. That would be pretty bad because you would not have any means to reach the languages other than the default one. The second problem is more general with all the API requests not linked to a user session. You would have no way to tell which language to use and that's a problem. This is the goal of the language prefix (or the URL parameter). So i don't think it makes sense trying to hide all.

Imo the feature that would be more interesting is the translation of slugs. You should look at qTranslate slug: https://github.com/not-only-code/qtranslate-slug. From what people have reported here, it seems it's still working decently well though it's not been maintained for years. Ideally we'd want to integrate it natively in qTranslate-XT but from now i prefer to keep it separate because this adds some extra work (more code, more people using it, more issues) and i don't have time with that for now. Better if we keep this topic for later after this project has migrated to a more stable place.

**Comment by Pandiora** [comment]
@herrvigg Thanks for reviving this project btw, I already gave up on making my blog multi-lang, until I read through the issues on qtranslate-X.

The plugin u mention might work, but imo there's a security-risk using such outdated plugins. It would be better to wait for this project to be merged into qtranslate-XT - at least for me. This would also benefit my urgent need to not use to much plugins and keep everything to the bare minimum - my future-me will thank me.

**Comment by shambolik** [comment]
@Pandiora and  @herrvigg thank you both very much for your detailed replies. I suspected that there would be some functional impracticalities with doing this but I wasn't knowledgeable enough to know without asking. I'm a PHP n00b but even if I wasn't I see that it would be counter-productive to do something like this. My motivation was not cosmetic (although it was a plus) but it was very specific and not important enough to warrant all the trouble this would potentially create. It was just for my landing page on a specific theme with a specific setting where pre-path mode was causing problems and I wanted to avoid query mode so as to be more SEO friendly (ironically). I think the more obvious thing to do here is talk with the theme developer about a workaround for the issue I'm having. Just thought this might be simpler... :$

@herrvigg indeed many thanks for reviving this project. I have tried a variety of multi-lang plugins and nothing is as practical and functional as qtranslate. Absolutely love it! The slug feature would indeed be cool but not something I would need so much as to warrant the security risk of an out-dated plugin like @Pandiora mentioned.

Thanks again to both you guys ;) I'm going to go ahead and close this (hope this is the correct thing to do, let me know if it is not).
