### ISSUE TITLE
Deprecated filter in WooCommerce order-received page

### ISSUE THREAD

**Issue by CNek** [qtranslate/qtranslate-xt#705]
Hello,
There is an issue with the latest WooCommerce :
"Notice: woocommerce_order_items_table is deprecated since version 3.0.0! Use woocommerce_order_details_after_order_table_items instead. "
### Quick fix :
_In qwc-front.php_

• Replace : woocommerce_order_items_table
• > With : woocommerce_order_details_after_order_table_items

**Comment by herrvigg** [comment]
Many thanks! Now fixed in the master branch.

Happy to see WooCommerce users actively participating! Since i don't use it this will help a lot to get back on track. As mentioned in https://github.com/qtranslate/qtranslate-xt/issues/686 i noticed some very old deprecated functions were still in the code, some that i fixed but there might still be some old stuff remaining.

There are still many open issues about WooCommerce. If you can help simply to check the status of the most recent ones (still a problem or not) this will help a lot to have a better overview of what is still to be done. Especially about the variable product attributes, the current status is quite unclear to me.

https://github.com/qtranslate/qtranslate-xt/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+woocommerce

You can comment directly on each of those open issues.
