### ISSUE TITLE
Jetpack related post title contains "Sorry, this entry is only available in ..."

### ISSUE THREAD

**Issue by dobek** [qtranslate/qtranslate-xt#716]
#699 solved untranslated titles problem in Jetpack related posts. However, now I can see "Sorry, this entry is only available in Polish." in the title which makes it messy. 

See:
https://blog.dobek.org/en/2019/meta-edukacja/#more-1062

Maybe it would be better to skip this message for title and make it available only for the . 
content of the post?

Personally, I'd love to disable "Sorry, this entry is only available in ..." message completely but I do not know how.

**Comment by dobek** [comment]
![Screenshot_20190731_211424](https://user-images.githubusercontent.com/226411/62240859-3aa96a80-b3d8-11e9-8280-ac726ec172b1.png)

**Comment by dobek** [comment]
This is what I'd expect. (It looks like this when I change the language.)

![Screenshot_20190731_211727](https://user-images.githubusercontent.com/226411/62241038-a2f84c00-b3d8-11e9-9f08-173c5251bd3f.png)

**Comment by herrvigg** [comment]
Well let's see more in details.

This happens when you switch to english. But the posts don't seem to have an english translation, so what is qT-XT supposed to show?

What surprises me is when you click on the related link, it opens the post with the polish title, not english. So i'm not sure what the title really holds in DB? Can you tell what is the raw content?

Normally the solution should be with the options / untranslated content (first tab), this one should be the most relevant: "Show post content in an alternative language when translation". The goal of this is to take the first available language (in the language order) as a fallback. Maybe this doesn't work well for the related posts.

Also check the one above "Hide posts which content is not available for the selected language". Generally it's better to keep it unchecked.

**Comment by dobek** [comment]
The value for English is blank. Only the value for Polish is set.

The fallback strategy would be good. It works for regular posts but it does not for Jetpack :(.

"Hide posts which content is not available for the selected language. " - is unchecked
"Show post content in an alternative language when translation is not available for the selected language." - is checked
Both are my preferred settings.

**Comment by herrvigg** [comment]
@dobek I just figured out this can be configured in the settings, by language!
- go in settings > languages > select your main language shown (Polish for you) > edit.
- change the very last field "Not available message" by putting a white space (or other).

An empty string is not allowed, I tried to remove the check but it's not a small change as qTranslate puts the default value back in that case! Currently there is this double possibility, both with the button "restore all default" and setting empty value separately for each field.

This would require deeper changes to restore the default values, better to keep the same philosophy everywhere for now. So the easiest is just to put a different value that you find less annoying 😄

**Comment by herrvigg** [comment]
Note i recently got rid of another annoying message in the content itself: https://github.com/qtranslate/qtranslate-xt/pull/655. Now it should be possible to change the remaining message. I'd say this ticket can be closed without a new patch (allowing an empty value is a more general problem beyond just this option).
