### ISSUE TITLE
Gutenburg support request

### ISSUE THREAD

**Issue by Dezueka** [qtranslate/qtranslate-xt#723]
Your plugin is very nice and better that wpml, but When this qtranslate xt will release the support Gutenburg version and make it is available  on WordPress repository plugin. I wait for you years now, it is still no gutenburg support. I do not want to use more plugins like Classic editor or disable gutenburg plugin na.

Look forward to get your update na

**Comment by herrvigg** [comment]
Thanks, happy to hear you prefer it despite many things still to be fixed. My first plan was to move to a new repo and deal with Gutenberg from that. In preparation to the migration there have been many urgent issues to fix with the modules.

Now it's in a better shape but i don't think we are ready for a migration. My main view on this is that i don't want to release a new plugin that is completely non-maintainable as it is currently now, especially in the core parameters and the JS code for the integration. Some radical changes and compatibility break (for integration) are necessary to restart from a healthier state and i do want them to happen before or during the migration, though i'm also considering a beta phase.

About Gutenberg i made some experiments some time ago that looked promising. I may go back to this now and maybe a support for Gutenberg could come out, possibly with some limitations but maybe that's more interesting for the short term. Also, the experimental branch has been available for months but i've had zero feedback on this, so if people want such feature it should involve more developers and testers.

**Comment by Dezueka** [comment]
I am will be your tester for this na, I use your plugin and work great with my site but only problem is the security test still not pass on the wpscan. It is unknown version and it said your plugin is still vulnerability that point the version back to old qtranslate version.

**Comment by herrvigg** [comment]
We'll come to Gutenberg hopefully in the short term but currently there are other quite problematic issues and stuff to clean up before being able to move forward.

One problem for Gutenberg is that i haven't found any way to reset the current block editor in the same session. The state is handled by React / redux but so far i don't know any simple way to update it. The switching buttons are available through the metaboxes API but they are almost pointless until this point is solved.

So the initial version may have some big limitations and only allow to edit each language separately, forcing to save the content before switching to another. The biggest drawback here is when the post is edited for the first time. But maybe there are other ways to deal with that in the session. However even this initial version requires some preparatory work also because the new API somehow forces to upgrade the JS client side to something more modern at least with ES 2015 and transpiling with babel. Therefore i prefer to do most of these changes first with the Classic Editor to avoid mixing all problems together.

**Comment by herrvigg** [comment]
Great news, I think i finally managed to get something working with **Gutenberg**!
Though there are some limitations, by forcing the editor more to single-language mode, this seems to work fine and it's suprisingly stable. Also, the auto-save should work (unlike the Classic Editor though this might be revisited).

Take it with reserves though, this is still in an experimental state. But I intend to pre-release this in a separate branch for testing possibly soon.

**Comment by Dezueka** [comment]
Thanks for your effort for us, you are brilliant and you are behind the success of connecting more localize WordPress & woocommerce people around the world. Thanks again Herrvigg.

**Comment by Dezueka** [comment]
If I am successful in my start up in Laos, I will support you forever for your effort. I have been using it for a while, and I will continue using it with my production size when you release the new version.

**Comment by herrvigg** [comment]
I have now released the 3.7.1 with many changes for REST, in anticipation of Gutenberg. Please validate this new version properly, hopefully with REST because this has to work well in order to use Gutenberg properly. 

If no critical bug with REST the initial-beta-Gutenberg version will follow very soon!

**Comment by herrvigg** [comment]
Closed by https://github.com/qtranslate/qtranslate-xt/issues/748 :)
