### ISSUE TITLE
Issue after update to 3.6.3

### ISSUE THREAD

**Issue by dlambova** [qtranslate/qtranslate-xt#738]
Hi,
Just updated to v 3.6.3 and now some warnings appear on top of my Wordpress dashboard and also on top of the Jetpack stats. I deactivated Jetpack but that didn't fix the issue. 

Deactivating temporarily qtranslate-XT resolved it and it appeared again after activation. 
During the Jetpack deactivation I got a completely blanc screen with the following warnings:
<img width="1274" alt="error after deactivating jetpack" src="https://user-images.githubusercontent.com/46216415/65993657-55f92a80-e49a-11e9-999d-6d705e70cccd.png">

The top 2 warnings are the ones maintained in the dashboard at all times:

<img width="1129" alt="error" src="https://user-images.githubusercontent.com/46216415/65993973-ff402080-e49a-11e9-8d58-f3d613e26e72.png">

The site seems to be working normally otherwise.

Any help or advice would be appreciated.

Thanks

**Comment by herrvigg** [comment]
@dlambova thank you for reporting this! And i know why this happens. 

The reason is that you are using this old legacy plugin "Integration: Yoast SEO & qTranslate-X" which is not maintained. The good news is that i have actually integrated it as a module in qTranslate-XT so you don't need it anymore 😎

With your current settings, if you go in the qTranslate options you will see that the Yoast SEO module can't be activated (actually you should already see a message in the admin pages... if it's not appearing you may just try to reactivate qTranslate-XT).

Anyway, if you disable the old "Integration: Yoast SEO & qTranslate-X" plugin, you should see the corresponding module for Yoast SEO activated. And the error will disappear. You can also delete this old plugin.

With the new module you should have the same functionalities as before. I know all is not working perfectly with Yoast SEO but it's not something new. For the evolutions there's some work to do. But if you see something regressing, you can open a new ticket here. 

Let us know how this works.

**Comment by dlambova** [comment]
Thank you so much! I wasn't aware about the Yoast SEO integration plugin.
I initially updated my PHP to a higher version and the headers disappeared but my site went blank. After deactivating the integration plugin it is all fine now.
Thanks for your support!

**Comment by bagaweb** [comment]
I'm probably missing something... I was looking for the Yoast SEO module but it doesn't show in the options...

![screenshot-localhost-2019-10-06-18-06-41-511](https://user-images.githubusercontent.com/14122970/66271979-4eec6680-e864-11e9-9fb7-fe55957ac2f1.png)

**Comment by herrvigg** [comment]
Ooops! I remember only now... i made some tries to migrate it when i was integrating all these legacy plugins but i had to remove because it was generating many errors and almost doing nothing. See #661. Sorry i completely forgot about this... my bad! 😅 

The code is there but the module is simply skipped. If you find courage you can retry by removing all the comments here:
https://github.com/qtranslate/qtranslate-xt/blob/51275c05cf589b4a40e1858118e04ec26bb4cab4/modules/qtx_modules_handler.php#L82-L88

As mentioned, there is some work to do on the JS side.

**Comment by bagaweb** [comment]
Thanks for the quick reply!
I will try to remove the comments right now and then report back.

**Comment by herrvigg** [comment]
What is sure is that the old legacy plugin generates errors such as the typo with QTX_EDITOR_SINGLE so it has to be disabled. But those won't happen with the new module. The existing JS errors are old because the legacy plugin was never maintained and i doubt it ever did something useful...

**Comment by bagaweb** [comment]
I tried Yoast SEO and I think that apart from the sitemap.xml functionality which is working, all the other functionalities do not work, for example SEO analysis, Readability analysis, option to edit meta description, and so on.
Better to leave the module commented IMHO.

**Comment by herrvigg** [comment]
Yes, thanks for testing.
I won't work on this now, but the module is now available so if anyone has more knowledge about Yoast SEO feel free to push some changes through pull requests. This is the purpose of having the new modules "in the house". It is now much easier to make some experiments.
