### ISSUE TITLE
Is there any alternative function instead of qtranxf_isAvailableIn()?

### ISSUE THREAD

**Issue by xxbxxqxx** [qtranslate/qtranslate-xt#745]
Hi, I'd like to set `<meta name=“robots” content=“noindex,nofollow”>` when a page doesn't have a translated text with the selected language.

I was trying to use "qtranxf_isAvailableIn()" but it was already removed in XT.

Do you know any other suitable functions for that situation?

Thanks.

**Comment by herrvigg** [comment]
Sorry about that.
I try to be very cautious with what i remove, since we are still in version 3 i try to keep the API unchanged and such a change should normally go through a deprecation phase... The only exception would be if i see the function is never used internally, neither in the modules or in the old qtranslate-slug. But in that case it was quite "brutal" for you.

The reason is removed that one, apart from not being used in the cases i mentioned, was because it makes a direct SQL call. In general i think this is bad practice. I don't think i will restore that function, but as a quick fix, the easiest for you is to rewrite the function as it was. You can simply copy this code and give it a different name:

```
function qtranxf_isAvailableIn( $post_id, $lang = '' ) {
	global $q_config;
	if ( empty( $lang ) ) {
		$lang = $q_config['default_language'];
	}
	global $wpdb;
	$post_content = $wpdb->get_var( $wpdb->prepare( "SELECT post_content FROM $wpdb->posts WHERE ID = %d", $post_id ) );
	if ( empty( $post_content ) ) {
		return false;
	}
	$languages = qtranxf_getAvailableLanguages( $post_content );
	if ( $languages === false ) {
		return $lang == $q_config['default_language'];
	}
	return in_array( $lang, $languages );
}
```

Sure i will not remove `qtranxf_getAvailableLanguages` ;)

**Comment by herrvigg** [comment]
About the API, this is really one of the biggest nightmare with qTranslate-XT. Everything is defined as global functions... it's really hard to have a worse situation... Believe me i would like to delete a million things but i can't because of that. The next major version will be ENTIRELY different, but this is likely not going to happen in this repo.

**Comment by herrvigg** [comment]
Ooops, you should actually not use the global q_config, this is very bad! Forget the original function. Here is a better one, but you can adapt it as you want:

```
function isAvailableIn_qTranslateXT( $post_id, $lang = '' ) {
	if ( empty( $lang ) ) {
		$lang = qtranxf_getLanguageDefault();
	}
	global $wpdb;
	$post_content = $wpdb->get_var( $wpdb->prepare( "SELECT post_content FROM $wpdb->posts WHERE ID = %d", $post_id ) );
	if ( empty( $post_content ) ) {
		return false;
	}
	$languages = qtranxf_getAvailableLanguages( $post_content );
	if ( $languages === false ) {
		return $lang == qtranxf_getLanguageDefault();
	}
	return in_array( $lang, $languages );
}
```

**Comment by xxbxxqxx** [comment]
@herrvigg 

Thank you so much for your kind reply!

Now I tried the code and it seems working fine, although sometimes it doesn't return 1 since 
 some of the pages on my website don't have lang code in the content.

Anyway, it's so helpful to understand the core code in the plugin.
I'll have a further look.
