### ISSUE TITLE
woocommerce-grouped-product-list-item and qTranslate-XT

### ISSUE THREAD

**Issue by websupportmd** [qtranslate/qtranslate-xt#756]
they are display problems!
the problem appears at group-product-list-item
how this problem can be solved
https://magazin.dekora.md/product/plinta-indo-01-alb-lucios/

**Comment by herrvigg** [comment]
It seems you have fixed it now, correct?

**Comment by websupportmd** [comment]
yes, solution https://stackoverflow.com/questions/50831883/qtranslate-x-woocommerce-grouped-products

**Comment by herrvigg** [comment]
Ahem, that's quite a nasty workaround. The `__()` function is only meant for static translation, not for dynamic content. It works only because this is hooked to a qtranslate function. Using `__()` does not make any sense, the content should be translated properly with hooks or at least call the proper qtranslate functions directly. But for now I don't have much time for these specific integration cases, this will certainly come back in the next versions.
