### ISSUE TITLE
Can't upload attachment in acf subfield on multi-language website

### ISSUE THREAD

**Issue by stefano88ita** [qtranslate/qtranslate-xt#772]
Hi! When i try to upload an attachment on a multi-language website with ACF, in the network call, after dragging a file in the media explorer, i get the following message "<b>Warning</b>:  call_user_func_array() expects parameter 1 to be a valid callback, class 'acf_qtranslate_acf_5_image' does not have a method 'wp_prepare_attachment_for_js' in <b>/var/www/html/wp-includes/class-wp-hook.php</b> on line <b>288</b><br />".

Resolved by commenting the line acf()->fields->register_field_type(new acf_qtranslate_acf_5_image($this->plugin));
in modules/acf/src/acf_5/acf.php:39

I don't know if can be a common issue! :)

My config: wp 5.3.1, acf pro 5.8.7, qtranslatext 5.3.1

**Comment by herrvigg** [comment]
@stefano88ita this should have been solved in #718 released with qTranslate-XT 3.6.2. We are now in 3.7.1.

It seems other people have the problem #783 and i don't see why. Are you the problem comes from qTranslate-XT? Could it be that you are using an old qTranslate-X/XT or the old legacy plugin [acf-qtranslate](https://github.com/funkjedi/acf-qtranslate)?

**Comment by stefano88ita** [comment]
I tested the current version right now (previously 3.6.1) and the issue has been solved with update.
Thank you for your very good job!

**Comment by herrvigg** [comment]
Great to read!
