### ISSUE TITLE
[Gutenberg] Remove admin notice

### ISSUE THREAD

**Issue by picasso** [qtranslate/qtranslate-xt#784]
Hi,

is there a way to remove admin notices?

These ones: 
`Caution! The block editor (Gutenberg) is only partially supported in qTranslate‑XT, yet experimental. Use at your own discretion! Alternatively, install and activate the Classic Editor in your plugins.`

`With the block editor (Gutenberg) only the single language mode is currently supported in qTranslate‑XT, which has been enforced. Review and save your options to remove this warning. Be sure to switch back if you turn back to the Classic Editor.`

Is there any reason why I should see them everyday? 
Thanks for help!

**Comment by herrvigg** [comment]
Yes i'm aware of that, i remove some of the previous features that were storing the user option in DB because i found it very messy. I didn't spend more time on this because these messages are supposed to go away at some point. Alternatively i could add a small feature to remove them client side through the browser Session storage, it's cleaner but the notices would come back if you switch browser or computer. Maybe the DB storage will come back, but it needed some refactoring anyway.

**Comment by herrvigg** [comment]
Now with the fix for #785 the second notice is gone, not used anymore :)
I will improve try the display for the first notice later.

**Comment by herrvigg** [comment]
I've changed the way the notice is managed.
- Now it appears once and if you close it, it will be remembered. If you don't have Classic Editor or alternative, a suggestion to install is added.
- If you reactivate later qTranslate-XT but you don't have Classic Editor or alternative, the message comes back. But you can close it and it will be remembered again.
