### ISSUE TITLE
[WC] Translations checkout and account settings

### ISSUE THREAD

**Issue by isoph** [qtranslate/qtranslate-xt#787]
Hi, thanks for your work, I’m starting to test a site with Woo Commerce + qTranslate-XT and I might have a few suggestions as I go along.

I’ve found two fields in the Woo Commerce Settings which I think should be translatable. In the Accounts & Privacy tab, under the Privacy policy sections, there are two texts displayed as privacy policies during registration and checkout. The field IDs are: `woocommerce_registration_privacy_policy_text` and `woocommerce_checkout_privacy_policy_text`.

**Comment by herrvigg** [comment]
Sure improvements are much welcome! If you want some good changes, please send PR (Pull Requests) with git. In the worst case you can copy the code here and someone interested in that part will hopefully create it from that.

**Comment by herrvigg** [comment]
I just realized these fields were already reported by @spleen1981  in https://github.com/qtranslate/qtranslate-xt/issues/608#issuecomment-439737898.

> * Woocommerce settings>Accounts & Privacy: "Registration privacy policy" and "Checkout privacy policy" are supposed to be translatable fields (anyway the qtranslate square brackets syntax is working).
> 

But other missing translatable options are also reported by @gm-style in https://github.com/qtranslate/qtranslate-xt/issues/608#issuecomment-487358085.

Since #608 concerns a lot of different issues, i will rather regroup in this ticket all the options fields i consider as "simple fields" that could be handled in a JSON configuration file (though it's done by PHP code in the WC module).  More advanced stuff is out of scope here.

Here is what i selected from the second comment:

> I noticed some integrations for translate fields are missing on these links:
> /wp-admin/admin.php?page=wc-settings&tab=checkout&section=bacs
> /wp-admin/admin.php?page=wc-settings&tab=checkout&section=cheque
> /wp-admin/admin.php?page=wc-settings&tab=checkout&section=cod
> /wp-admin/admin.php?page=wc-settings&tab=checkout&section=paypal
> 
> I discovered the issue into the file "qwc-admin.php" of WC module, where the arrays of fields to be translated refers to pages:
> ....section=wc_gateway_bacs, ....section=wc_gateway_cheque, etc.
> WooCommerce changed these queries in recent versions, cause of settings pages design rework. While these fixes are easy by just adding a new array for new queries, another issue is for the new shipping settings tab, because it can add multiple lines of configurations, where queries are created with line IDs, like: ....tab=shipping&zone_id=1 .
> Plus the configuration name has to be inserted into a popup. I'm trying to fix this.

**Comment by herrvigg** [comment]
Fixed in [3.7.3]( https://github.com/qtranslate/qtranslate-xt/releases/tag/3.7.3)
