### ISSUE TITLE
Filter qtranslate_language_detect_redirect

### ISSUE THREAD

**Issue by ivanorischenko** [qtranslate/qtranslate-xt#801]
Hi. I need to change redirect status code for hide default lang prefix. 
I found filter 'qtranslate_language_detect_redirect', but your plugin inited before load theme. This makes it impossible to change the behavior.

**Comment by herrvigg** [comment]
Yes the redirect handling is done on `plugins_loaded` and i can't really change this, any change even on the priority would lead for sure to regressions. You won't be able to handle it with it theme because the `functions.php` for the themes are loaded later. If you want to act `qtranslate_language_detect_redirect` you have to create a plugin (or a mu-plugin), it's the only way.

Btw what do you want to achieve? Hide default lang prefix should normally be handled by QTX.
