### ISSUE TITLE
Compatibility with All in One SEO Pack Pro

### ISSUE THREAD

**Issue by nalato** [qtranslate/qtranslate-xt#845]
The Pro version of All in One SEO Pack manage SEO for Categories, Tags and Custom Taxonomies.
Current version of Qtranslate XT enables multilingual framework only for post pages (post.php).
I modify qtranslate-xt/modules/all-in-one-seo-pack/ and I add term.php.
It seems works.

**Comment by herrvigg** [comment]
?

**Comment by nalato** [comment]
I modify the 10 row of qtranslate-xt/modules/all-in-one-seo-pack/
$page_config['pages'] = array( 'post.php' => '' ); 
à
$page_config['pages'] = array( 'post.php' => '', 'term.php' => '' );
to add translation compatibility to terms page (Categories, Tags and Custom Taxonomies).

**Comment by herrvigg** [comment]
@nalato are you sure it is `term.php`? Shouldn't it be `edit-tags.php`? I got an automatic redirection.

What features do you have with All in One SEO Pro? With the free version there is nothing so i can't test.

**Comment by nalato** [comment]
@herrvigg All in One SEO Pro add capability to manage SEO tags for for Categories, Tags and Custom Taxonomies (standard version manage only post and pages).
I modify  qtranslate-xt/modules/all-in-one-seo-pack/qaioseop-admin.php
`term.php` is the page to manage custom taxonomy. `edit-tags.php` works already fine.

**Comment by herrvigg** [comment]
But there is no specific entry for `edit-tags.php`, how can this work for such page?
The goal of the admin config is to add hooks for example for `aiosp_title`, `aisop_description`, ... 

Currently there are only added for `post.php` and `admin.php?page=all-in-one-seo-pack/aioseop_class.php`, which is similar to `post.php` but it uses a `aiosp_home_ ` prefix instead of `aisop_` and there is no entry equivalent to `aiosp_custom_link`. Maybe it's missing.

**Comment by herrvigg** [comment]
More likely due to v4 than pro, every item that had id `aiosp_` does not exist anymore, for example `aiosp_title`.

@nalato to close this ticket, would it be enough to add `term.php`? I'm a bit confused with `edit-tags.php`, when you say it works is that also for AIOSEO (pro)? Does AIOSEO still work for you?

**Comment by nalato** [comment]
Hello @herrvigg,
AIOSEO pro works fine for me by adding `term.php`.
`edit-tags.php` is the list page template, `term.php` is the single term page template (category, tag, custom taxonomy).
AIOSEO add SEO fields in the single term page.

**Comment by herrvigg** [comment]
OK i pushed the change you requested. I'm not sure this works with AIOSEO v4 but this "term.php" will certainly be needed according to your comments. Anyway it doesn't cost much to have.

**Comment by herrvigg** [comment]
Fix released in 3.9.2

**Comment by bagaweb** [comment]
I've still had to manually add those lines in https://github.com/qtranslate/qtranslate-xt/issues/933 to make it work properly.

**Comment by herrvigg** [comment]
@bagaweb but that's two different problems. See my comments above, the change that was requested is merged. The other issue is still open and it's a more general problem for V4. I suggest we keep this one closed.

**Comment by bagaweb** [comment]
Sorry I misunderstood. Hopefully everything will fixed soon.
