### ISSUE TITLE
[WC]Coupon codes appear with [:] after upgrade to WP 5

### ISSUE THREAD

**Issue by ahsipila** [qtranslate/qtranslate-xt#883]
Coupon codes in Woocommerce appear with [:]-tags after upgrade to WP 5 - I have downgraded to 4.9.13 and can note that the problem does not exist there. See attached.
This is very serious for shopkeepers, as the coupons are a major marketing tool and coupons with [:]-tags are not user friendly.

![Screenshot 2020-09-10 at 12 11 23](https://user-images.githubusercontent.com/27296969/92709187-6038cf80-f35f-11ea-9467-e7672ac6588d.png)

**Comment by ahsipila** [comment]
This is true at least for WP 5.4.1 and later. I will investigate 5.3

**Comment by ahsipila** [comment]
UPDATE: if the coupon code is entered with exactly the same text in both Finnish and English, then the coupon will appear as it should, even with WP 5.5.1., otherwise the coupon will appear with the [:]-tags,as indicated above. So this is workaround at least.

**Comment by herrvigg** [comment]
Important question: should the coupon really be translated? I don't think so! See: https://github.com/qtranslate/qtranslate-xt/issues/61. Allowing translations here may break many functionalities related to the handling of the coupon value. If you agree with that we should disable the translation feature here.

At the same time, I also notice that the coupon description is not translated. So this is the opposite.

**Comment by herrvigg** [comment]
If you look in #61 they actually found the same workaround as you. But now i understand this is not so trivial to fix. When you create the coupon the URL is quite specific with `post-new.php?post_type=shop_coupon`.

The problem is when you edit the coupon again, then the URL becomes entirely generic and the form fields don't contain any special attribute or meta tag that would allow to do such filtering. This requires certainly a few changes first on the server side to add this information and then on the client side to handle this.

In fact they marked this as enhancement in the past, and i believe the exclusion of this kind of fields should rather be a generic functionality and we would just add one use case here.

**Comment by herrvigg** [comment]
Also this problem doesn't look related to a specific version of WordPress, there was an issue already in... 2015.

**Comment by ahsipila** [comment]
Thanks for the comments - yes, I believe I was mistaken by the relation to WP version - my client alerted me after upgrade, so I was fixed on that. I guess we can live with the workaround.
