### ISSUE TITLE
missing qtranslate.php version bump to v3.9.0

### ISSUE THREAD

**Issue by X-Raym** [qtranslate/qtranslate-xt#885]
Hi,
seems you forgot to set https://github.com/qtranslate/qtranslate-xt/blob/master/qtranslate.php#L6 as v3.9.0, it is still 3.8.1.

Best,

**Comment by herrvigg** [comment]
My bad!! I *knew* i was forgetting something... github updater is not going to like this and may go in loop. 

To try to fix this without a full new release, i just amended the last commit, re-tagged and force pushed all.
I know this should be avoided but nothing else changed apart from that version number in qtranslate.php.
For those who already pulled with git you may need a `git reset --hard origin/master`.
Sorry about the inconvenience!

If this creates too much problem i will create a new 3.9.1 release.

**Comment by X-Raym** [comment]
> If this creates too much problem i will create a new 3.9.1 release.

Well, maybe it is the less confusing thing to do. :P Not too much trouble.

I personally just version bumped manually right in the file.

Thanks for your support !

**Comment by herrvigg** [comment]
Yes you can also do like this locally, as long as you don't work with git on this repo and pulled before this fix (otherwise do git reset as described earler). But this should concern few people.
I wanted to avoid an "empty/fake release". I hope my new commit can adjust all those using github updater, if there is a version mismatch it should download again the whole release from master and get the correct version this time (the version in qtranslate.php must match the git tag).

**Comment by X-Raym** [comment]
@herrvigg Ok, you decide ! I consider this issue fix. You can close it when you want. Thx for quick support !

**Comment by herrvigg** [comment]
I left it open a bit for visibility but it seems there are no more problem so let's close it.
