### ISSUE TITLE
wrong flag Serbia

### ISSUE THREAD

**Issue by stevr1it** [qtranslate/qtranslate-xt#913]
Hello we have noticed you have add a wrong falg for serbian country, how cna we change it? we need it. thank you

**Comment by TheHeat** [comment]
Hi @stevr1it do you mean the flag is there but wrong (has changed since it was added to the list) or that the flag is for the wrong country?

If the latter, then it's possible to change the flag in the language settings. 

<img width="617" alt="Screenshot 2020-11-06 at 14 04 24" src="https://user-images.githubusercontent.com/1839633/98374732-03912280-2039-11eb-8794-7469cc7ac6c8.png">
Click the **Edit** link next to the language

<img width="617" alt="Screenshot 2020-11-06 at 14 04 02" src="https://user-images.githubusercontent.com/1839633/98374780-186db600-2039-11eb-97e3-f714cc67b962.png">
Find your flag from the select box

For what it's worth, there are lots of very good arguments against using flags to represent languages. Here in the UK for instance we have a number of minority languages including Welsh that all 'belong' to the United Kingdom - so the Union Flag is really not an appropriate symbol for English. I'm sure given the number of Spanish speakers around the world that the Spanish flag is probably not appropriate there either. Great link on the subject here: http://www.flagsarenotlanguages.com

**Comment by TheHeat** [comment]
Just had a little look into this and it looks like there is no Serbian flag in the plugin. There's a flag for **sb** which is the Solomon Isles, but the language code for Serbia is **srb** I've got a file I can commit if you're happy with it

![srb](https://user-images.githubusercontent.com/1839633/98376888-09d4ce00-203c-11eb-84a3-cbf32856bc1f.png)

**Comment by stevr1it** [comment]
Hello the wrong flag for serbia. Serbia has another flag, how can i 
change it? thank you

Il 06/11/20 15:11, Marc Heatley ha scritto:

**Comment by stevr1it** [comment]
yes thank you

Il 06/11/20 15:26, Marc Heatley ha scritto:

**Comment by herrvigg** [comment]
hello,
the Serbian flag is there but it's named `rs.png` 
https://github.com/qtranslate/qtranslate-xt/blob/master/flags/rs.png

The Serbian language is `sr` but the `sr` flag is the one for Suriname.
https://github.com/qtranslate/qtranslate-xt/blob/master/flags/sr.png

It's a problem of different ISO standards:
- the flags follow a ISO-3166 (country and regions)
- the languages are ISO-639 (languages). 

Maybe we should keep this as it is, but i'm not 100% sure.

**Comment by herrvigg** [comment]
Finally i'm convinced we should keep it as it is, the language code is one thing, the country/region is another. The flag is associated to the country. We don't have a default entry for Serbian, but that is another topic.

Conclusion: the Serbian flag is already available, you can find it under name `rs.png`.

@stevr1it i propose we close this ticket. You can still comment on it. We can re-open it if needed.
