### ISSUE TITLE
Page showing up 404 erros and 'not found'

### ISSUE THREAD

**Issue by zallaevan** [qtranslate/qtranslate-xt#948]
I installed this plugin long ago, and it worked flawlessly, until some days ago. I wanted to migrate to another host, but I realized that the website isn't displaying the blog correctly, although the backend (wp-admin) looks to be ok (so it isn't WP's problem). Also, I've set the languages to appear with their corresponding subdir, like English: /en/, etc. Also, if I want to access the main page in another language, if I type site.com/en/, it doesn't show up (not found error).

Thanks in advanced.

WP version: 5.4.4; qT-XT version: 3.9.2

**Comment by herrvigg** [comment]
This is impossible to debug without further investigation from your side. You can find a few tips here: https://github.com/qtranslate/qtranslate-xt/wiki/Troubleshooting

This doesn't look like a problem in qTranslate-XT directly. You may have something wrong with the redirections but it could be something completely different.

Sorry but I close this ticket for now since it's way too generic.
