### ISSUE TITLE
qTranslate XT and ACF frontend forms compatibility

### ISSUE THREAD

**Issue by pinkarman** [qtranslate/qtranslate-xt#985]
I am trying to set up an ACF frontend form with ACF fields and I noticed a couple issues:
1 - multilanguage textareas show only the current language, if I click the language tabs nothing happens.
2 - since there are no radio buttons in qTranslate-XT ACF, I tried to add language shortcodes like [:en] [:it] [:] to a standard ACF radio button. It works great for backend ACf, while in the frontend those radio buttons are rendered as a single line text input. I fear the same issues could happen with checkboxes and select dropdowns.

**Comment by MK-RD** [comment]
Maybe you have to get creative here and create the relevant ACF fields in several languages in order to then display them in the frontend in a language-specific manner.

**Comment by MK-RD** [comment]
Negative, both textarea (QTX-ACF) and WYSIWYG editor (ACF) are translated. For ACF, however, the setting (ACF qTranslate) "Enable translation for Standard Field Type" must be activated.

Currently I would suggest the Textarea (QTX-ACF), because there is a follow-up problem with the WYSIWYG-Editor (ACF) in connection with the browser cache, which can be solved via a hack.

**Comment by herrvigg** [comment]
With ACF Pro 5.12.2 it seems the ACF "Wysiswyg Editor" is not working though "Enable translation for Standard Field Type" is enabled (see #1186).

> there is a follow-up problem with the WYSIWYG-Editor (ACF) in connection with the browser cache, which can be solved via a hack.

@MK-RD What is the cache problem? Can you explain more about that hack?

**Comment by herrvigg** [comment]
I close this ticket since I don't see anything specific here. The issue with Wysiswyg standard editor remains open, see #1186 .
