### ISSUE TITLE
502 Bad Gateway with ultra fast PHP

### ISSUE THREAD

**Issue by valerensi** [qtranslate/qtranslate-xt#986]
Hello, 
we have a problem inside a project.
The client has tell us that various customer saw a 502 Bad Gateway error when they try to view the website. 
We have asked to our server supply to have a look at this issue.
They reported that it is related to qtranslate-xt. I paste here their feedback:

_The problem you are facing is related with the PHP version (7.3.27) or the PHP setup of the site which is currently set to PHP Ultraveloce. It seems that the plugin in question is not fully compatible with PHP Ultrafast or the PHP version which might lead to intermittent 502 Bad Gateway errors.

Here the log details (I have replace the name of the website).

[26-Mar-2021 10:54:22 UTC] PHP Warning:  assert(): detected in parse_language_info - cancelled by can_redirect, url_info={
    &quot;cookie_lang_front&quot;: &quot;it&quot;,
    &quot;cookie_front_or_admin_found&quot;: true,
    &quot;scheme&quot;: &quot;https&quot;,
    &quot;host&quot;: &quot;www.sitename.com&quot;,
    &quot;path&quot;: &quot;\/it\/&quot;,
    &quot;query&quot;: &quot;wc-ajax=aws_action&quot;,
    &quot;path-base&quot;: &quot;&quot;,
    &quot;doing_front_end&quot;: true,
    &quot;wp-path&quot;: &quot;\/&quot;,
    &quot;lang_url&quot;: &quot;it&quot;,
    &quot;language&quot;: &quot;it&quot;,
    &quot;doredirect&quot;: &quot;detected in parse_language_info - cancelled by can_redirect&quot;,
    &quot;set_cookie&quot;: true
} failed in sitename/public_html/wp-content/plugins/qtranslate-xt-master-393/qtranslate_core.php on line 105_

==

To solve we have now removed PHP ultrafast module. We keep monitoring in the next days.
Anyone has experienced this problem?
Thanks.

**Comment by herrvigg** [comment]
I don't know the specificities about PHP ultrafast. From what you sent I understand that:
- it's an ajax request considered as a front_end request
- it wants to redirect because it's not happy with the language but I can't see why (the cookie and lang seem to match)
- it cannot redirect due to qtranxf_can_redirect and therefore it triggers the assert fail. That is a safeguard I put on purpose to detect such cases. You may remove the assert (comment line 105) just to test but then the language state is inconsistent so I don't know what would happen next, difficult to predict.

The reason it does not allow to redirect comes certainly from the ajax request so I suppose `wp_doing_ajax` is handling correctly that case. The main question is to understand why it wants to redirect despite having the language cookie matching the lang_url. That's really weird.

**Comment by valerensi** [comment]
Ok @herrvigg thanks for your help. We try to remove the line 105.

**Comment by herrvigg** [comment]
Related to #1326.

**Comment by herrvigg** [comment]
Fix released in 3.14.2.
