### ISSUE TITLE
integrations and updates

### ISSUE THREAD

**Issue by germig** [qtranslate/qtranslate-xt#993]
To update it, will it work unstalling the current qtranslate xt version and install the new one?
And for integration? any suggestions to integrate the qtranslate-xt to qtranslate slug and Yoast SEO ?
thanks

**Comment by herrvigg** [comment]
As mentioned in the [README](https://github.com/qtranslate/qtranslate-xt#how-to-update-qtranslate-xt-with-the-last-release), it is recommended to use github updater. This will keep your install updated with the last release. If you want to use the very last version in development you can clone directly this repo with github.

qtranslate slug is working but it's still a separate plugin, it might be fully integrated [some day](https://github.com/qtranslate/qtranslate-xt/issues/671).
There is a module for Yoast SEO though there are some limitations with the UI.

**Comment by herrvigg** [comment]
Note also about the uninstallation: https://github.com/qtranslate/qtranslate-xt/wiki/FAQ#uninstall
The ML tags and settings remain in the DB, there is no cleanup functionality yet.
You can delete the folder and overwrite at any time but for the common usage github updater is the recommended solution.

**Comment by germig** [comment]
thank you for your replies. 
After installing github updater on my wp-admin, where should I add those code lines. Which header? I didn't understand this.
"Your plugin or theme must contain a header in the style.css header or in the plugin's header denoting the location on GitHub."

thanks again.

**Comment by herrvigg** [comment]
Did you follow the installation steps described in the [README](https://github.com/qtranslate/qtranslate-xt/blob/master/README.md#installation)?
You should clone the repo once from this github, either from the last release (safest solution) or master if you want to start from the very last updates.
Then github updater is just one way to keep your versions updated since we have no official repo on WordPress yet (we have to decide for the name of the plugin).

**Comment by germig** [comment]
the other issue is the qtranslate slug. I cannot make it work with the XT version. Any suggestions?
thanks again
